# Generated by Django 4.2.5 on 2023-09-27 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charcode', models.CharField(max_length=8, verbose_name='Буквенный код')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
        migrations.CreateModel(
            name='CurrencyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Значение в рублях')),
                ('date', models.DateField(verbose_name='Дата обновления курса')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курс валют',
            },
        ),
        migrations.CreateModel(
            name='TrackedQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Пороговое значение')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.currency', verbose_name='Котируемая валюта')),
            ],
            options={
                'verbose_name': 'Отслеживаемая валюта',
                'verbose_name_plural': 'Отслеживаемые котировки',
            },
        ),
    ]
