# Generated by Django 4.2.5 on 2023-09-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='charcode',
            field=models.CharField(max_length=8, unique=True, verbose_name='Буквенный код'),
        ),
    ]
